### ISSUE TITLE
restrict vpn traffic only, currently all internet traffic routed

### ISSUE THREAD

**Issue by encryptblockr** [Nyr/openvpn-install#692]
i will like to only allow vpn traffic to be routed via the openvpn connection and NOT route all internet traffic. What steps do i need to take to achieve this?

Thanks!

**Comment by thejohnha** [comment]
Comment out `push "redirect-gateway def1 bypass-dhcp"` in `/etc/openvpn/server/server.conf`

**Comment by encryptblockr** [comment]
after i comment it out what command do i run next or will it automatically update?

**Comment by encryptblockr** [comment]
@thejohnha do i have to restart the service? if yes then what is command to restart?

thanks

**Comment by Nyr** [comment]
`systemctl restart openvpn-server@server.service`

**Comment by encryptblockr** [comment]
```
systemctl restart openvpn-server@server.service
Failed to restart openvpn-server@server.service: Unit openvpn-server@server.service not found.
```

@Nyr

**Comment by Nyr** [comment]
`systemctl restart openvpn@server.service`

**Comment by encryptblockr** [comment]
@Nyr now i cant reach anything anymore

Commented out `push "redirect-gateway def1 bypass-dhcp"` in `/etc/openvpn/server/server.conf`

and ran 

`systemctl restart openvpn@server.service`

**Comment by Nyr** [comment]
That combination of the old service file with the new `server.conf` location and Ubuntu 16.04, couldn't be obtained if you were using my script.

So please, seek help elsewhere, this issue tracker is for my project only.

**Comment by encryptblockr** [comment]
i used your script to set this up

`wget https://git.io/vpn1604 -O openvpn-install.sh && bash openvpn-install.sh`

**Comment by encryptblockr** [comment]
> @Nyr
> now i can NO longer reach anything anymore
> but the VPN connects still
> 
> Commented out `push "redirect-gateway def1 bypass-dhcp"` in `/etc/openvpn/server/server.conf`
> 
> and ran
> 
> `systemctl restart openvpn@server.service`

now i removed the comment and ran restart service again and now its back to working well
so means commenting that line does not work @thejohnha

**Comment by thejohnha** [comment]
It works fine. I used it this week.

**Comment by encryptblockr** [comment]
also i have another one that is centOS 7

commented out in the line in `/etc/openvpn/server/server.conf`

and restarted service `systemctl restart openvpn-server@server.service`

service for restarted but then when i login VPN connects fine but can't reach anything

do i need to add a route or how does client and VPN know when to route traffic to VPN and when to do regular internet?

**Comment by Nyr** [comment]
> so not sure why you saying that

Because that version of the script uses `/etc/openvpn/server.conf` and you mentioned editing `/etc/openvpn/server/server.conf`.

Anyway, we already told you how to do it. If you still are unable, I'm sorry but this is an issue tracker, not a support forum. You'll need to seek help elsewhere.

**Comment by encryptblockr** [comment]
> > so not sure why you saying that
> 
> Because that version of the script uses `/etc/openvpn/server.conf` and you mentioned editing `/etc/openvpn/server/server.conf`.
> 
> Anyway, we already told you how to do it. If you still are unable, I'm sorry but this is an issue tracker, not a support forum. You'll need to seek help elsewhere.

ok was typo then as i copied what @thejohnha posted 
i meant this file for the Ubuntu 16.04 one `/etc/openvpn/server.conf`

either way the centOS 7 one not working either

**Comment by thejohnha** [comment]
I referenced the conf file that's used by the current version of this script. If your machine is running something else YMMV.

**Comment by encryptblockr** [comment]
**ubuntu 16.04 LTS** 
`/etc/openvpn/server.conf`and restart is 
`systemctl restart openvpn@server.service`

**centOS 7** 
`/etc/openvpn/server/server.conf` and restart is 
`systemctl restart openvpn-server@server.service`


but that is solved now..issue is when i restart i connect to VPN fine but cant route to anything remotely

**Comment by encryptblockr** [comment]
ok here is what i have
let me know what am doing wrong
`10.1.0.5` is local ip the openvpn server machine
as you can see i commented this line `#push "redirect-gateway def1 bypass-dhcp"`

`cat /etc/openvpn/server/server.conf`

```
local 10.1.0.5
port 1194
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
#push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nobody
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
explicit-exit-notify
```

and then restarted openvpn

```
systemctl restart openvpn-server@server.service
```


then when i try to connect, VPN connects but i can't reach anything on the remote network.
do i need to make any changes on my client machine or anything else am missing?

when i remove the comment everything works like a champ.

**Comment by Nyr** [comment]
All that removing the `redirect-gateway` parameter will accomplish, is to stop outgoing traffic from being redirected over the VPN. I understand that you are still having issues with your setup, but they are not an issue with this project.

I've already insisted that this is an issue tracker and not your personal OpenVPN helpdesk, so I'm locking this conversation.
